### ISSUE TITLE
JLCPCB: SMT Assembly

### ISSUE THREAD

**Issue by Strech** [tominabox1/Le-Chiffre-Keyboard#5]
Hey, @tominabox1 thanks a lot for open-sourcing this amazing keeb. I'm trying to order the PCB and Plate in JLCPCB but I'm lacking knowledge about PCB parts.

When you order on JLCPCB they offer almost free SMT Assembly and they ask you about 2 things "BOM File" and "CPL File", do you have those? Or can you name components and their count to build the PCB?

**Comment by tominabox1** [comment]
for what it's worth, there's a group buy going on right now at https://p3dstore.com. You may want to do this instead, it'd probably amount to a good savings (if you're in the US) over 5 assembled boards.

You'll need to export the BOM and part location file from the Kicad project https://support.jlcpcb.com/article/84-how-to-generate-the-bom-and-centroid-file-from-kicad

**Comment by Strech** [comment]
Thanks for the GB link, unfortunately, I'm in the EU and the 35$ PCB will be converted to 80$ with delivery (before taxes, sic!). But I'm doing it not for saving money, but as a COVID lockdown hobby.

**Comment by Strech** [comment]
@tominabox1 Sorry for bothering you again, I think I manage to understand most of the components on the board except 2

```
F1    Polyfuse_Small      Keebio-Parts:Fuse_0805
Y1    Crystal_GND2        Keebio-Parts:Crystal_SMD_3225-4pin_3.2x2.5mm
```

I think I found [`Y1`](https://jlcpcb.com/parts/componentSearch?searchTxt=Crystal%20SMD%203225) and [`F1`](https://jlcpcb.com/parts/componentSearch?searchTxt=fuse%200805) but there are so many options. May I ask you to help me to choose them?

**Comment by tominabox1** [comment]
This fuse should be good 
https://lcsc.com/product-detail/Surface-Mount-Fuses_0-5A-6V-Self-healing-fuse_C66452.html/?href=jlc-SMT

This crystal
https://lcsc.com/product-detail/SMD-Crystal-Resonators_Yangxing-Tech-X322516MRB4SI_C70562.html/?href=jlc-SMT

**Comment by Strech** [comment]
Thanks, I appreciate your help, was a bit challenging for me to understand how to use Kicad and Eeschema, if you want I can try to open PR with a filled LCSC field and/or BOM files

**Comment by tominabox1** [comment]
feel free to open a PR

**Comment by Strech** [comment]
@tominabox1 👋🏼 Hey, it's me ... again. The microcontroller which was specified unfortunately is out of stock on JLCPCB, and I'm not brave enough to just replace it with another. I tried comparing them, but I didn't see a severe difference (and my fear it's because I don't understand it).

May I ask you which chip can replace `ATMEGA32U4-AU` from [this list of ATMEGA32](https://jlcpcb.com/parts/componentSearch?searchTxt=ATMEGA32)? If none, then I will wait till they re-stock (check the stock column).
