### ISSUE TITLE
duplicate mfg part numbers

### ISSUE THREAD

**Issue by dayofdoom** [tominabox1/Le-Chiffre-Keyboard#7]
Hello,

In the BOM on the main page, these two components have the same MFG part number but are listed as seperate components.

3 | R6, R5 | 2 | 0805W8J0103T5E | 10k | 0805
-- | -- | -- | -- | -- | --
4 | R4, R3 | 2 | 0805W8J0103T5E | 22r | 0805

Thank you

**Comment by tominabox1** [comment]
Thanks for the report. I have updated the BOM with the correct numbers

**Comment by dayofdoom** [comment]
Thank you!
